/**
 Copyright 2024 csx - @yunkss/ef_core

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/**
 * @Author csx
 * @DateTime 2024/4/25 20:39:04
 * @TODO CommonConst  公共常量
 * @Use 详细使用方法以及文档详见ohpm官网,地址https://ohpm.openharmony.cn/#/cn/detail/@yunkss%2Fef_core
 */
export class CommonConst {
  /**
   * 引号
   */
  static readonly quot: string = "\"";
  /**
   * 大于
   */
  static readonly gt: string = ">";
  /**
   * 小于
   */
  static readonly lt: string = "<";
  /**
   * 等于
   */
  static readonly eq: string = "=";
  /**
   * 冒号
   */
  static readonly mh: string = ":";
  /**
   * 逗号
   */
  static readonly dh: string = ",";
  /**
   * 左花括号
   */
  static readonly zkh: string = "{";
  /**
   * 右花括号
   */
  static readonly ykh: string = "}";
  /**
   * 左中括号
   */
  static readonly zzkh: string = "[";
  /**
   * 右中括号
   */
  static readonly yzkh: string = "]";
}