/**
 * @Author csx
 * @DateTime 2024/4/25 20:39:04
 * @TODO CommonConst  公共常量
 */
export class CommonConst {
  /**
   * 引号
   */
  static readonly quot: string = "\"";
  /**
   * 大于
   */
  static readonly gt: string = ">";
  /**
   * 小于
   */
  static readonly lt: string = "<";
  /**
   * 等于
   */
  static readonly eq: string = "=";
  /**
   * 冒号
   */
  static readonly mh: string = ":";
  /**
   * 逗号
   */
  static readonly dh: string = ",";
  /**
   * 左花括号
   */
  static readonly zkh: string = "{";
  /**
   * 右花括号
   */
  static readonly ykh: string = "}";
  /**
   * 左中括号
   */
  static readonly zzkh: string = "[";
  /**
   * 右中括号
   */
  static readonly yzkh: string = "]";
}