/**
 * @Author csx
 * @DateTime 2024/1/3 20:45
 * @TODO DateConst  日期格式的常量
 */
export class DateConst {
  static YMD: string = "yyyyMMdd";
  static HMS: string = "HH:mm:ss";
  static HM: string = "HH:mm";
  static YMD_HLINE: string = "yyyy-MM-dd";
  static YMD_HLINE_HMS: string = "yyyy-MM-dd HH:mm:ss";
  static YMD_HLINE_HM: string = "yyyy-MM-dd HH:mm";
  static YMD_BLINE: string = "yyyy/MM/dd";
  static YMD_BLINE_HMS: string = "yyyy\\/MM\\/dd HH:mm:ss";
  static YMD_BLINE_HM: string = "yyyy\\/MM\\/dd HH:mm";
}