/**
 * @Author csx
 * @DateTime 2024/1/24 19:35
 * @TODO UiConst  UI界面所需的常量
 */
export class UiConst {

  /**
   * 弹出提示类显示时间
   */
  static readonly ANIMATION_DURATION: number = 1500;

  /**
   * dialog标题
   */
  static readonly DIALOG_TITLE: string = '温馨提示';

  /**
   * dialog确定文字
   */
  static readonly DIALOG_OK: string = '确定';

  /**
   * dialog取消文字
   */
  static readonly DIALOG_CANCEL: string = '取消';

  /**
   * dialog确定颜色
   */
  static readonly DIALOG_OK_COLOR: string = '#409eff';

  /**
   * dialog取消颜色
   */
  static readonly DIALOG_CANCEL_COLOR: string = '#606266';
}