/**
 * @Author csx
 * @DateTime 2024/1/24 19:35
 * @TODO UiConst  UI界面所需的常量
 */
export class UiConst {

  /**
   * 弹出提示类显示时间
   */
  static readonly ANIMATION_DURATION: number = 2000;

  /**
   * dialog标题
   */
  static readonly DIALOG_TITLE: string = '温馨提示';

  /**
   * alert标题
   */
  static readonly ALERT_TITLE: string = '警告提示';


  /**
   * action标题
   */
  static readonly ACTION_TITLE: string = '操作菜单';

  /**
   * dialog确定文字
   */
  static readonly DIALOG_OK: string = '确定';

  /**
   * dialog取消文字
   */
  static readonly DIALOG_CANCEL: string = '取消';

  /**
   * dialog确定颜色
   */
  static readonly DIALOG_OK_COLOR: string = '#409eff';

  /**
   * alert 确定按钮文本颜色
   */
  static readonly ALERT_OK_COLOR:string = "#fff";

  /**
   * alert 确定按钮背景颜色
   */
  static readonly ALERT_OK_BG_COLOR:string = "#409eff";

  /**
   * alert 取消按钮文本颜色
   */
  static readonly ALERT_CANCEL_COLOR:string = "#fff";

  /**
   * alert 取消按钮背景颜色
   */
  static readonly ALERT_CANCEL_BG_COLOR:string = "#dcdfe6";

  /**
   * dialog取消颜色
   */
  static readonly DIALOG_CANCEL_COLOR: string = '#606266';



}