/**
 Copyright 2024 csx - @yunkss/eftool

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/**
 * @Author csx
 * @DateTime 2024/6/11 12:37:06
 * @TODO CustomDialog  高级组件自定义弹框工具类
 * 参考链接 https://developer.huawei.com/consumer/cn/forum/topic/0201150581656599021
 *
 */
export class CustomDialog {

  //完善弹框  参考https://gitee.com/harmonyos_samples/custom-dialog-gathers
  //https://gitee.com/harmonyos_samples/component-collection

  // https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-arkui-componentcontent-V5  API12

}